service:
  name: academics
  displayName: Pinnacl Project - Academics Service
  address: io.pinnacl.academics
  sharedData:
    enabled: true
    extraMaps:
      - gateway
      - refreshTokens
      - totps
      - languages

observability:
  enabled: true
  port: 9092
  metrics:
    enabled: true
    path: /metrics
  k8s:
    enabled: true
    probes:
      liveness: /health/live
      readiness: /health/ready


storage:
  db:
    host: localhost
    port: 6550
    name: academics
    user: pain
    password: almighty-push
    url: jdbc:postgresql://localhost:6550/academics
    useTls: false
    certPath: /tmp/dummy-cert.pem
    maxPool: 5
    migration:
      enabled: true
      changelogPath: migrations/changelog/db.changelog-dev.xml


features:
  verticles:
    service:
      address: service.details
      messageTypes:
        - name: academicsVersion
          broadcastable: false
        - name: academicsHealthLive
          broadcastable: false
        - name: academicsHealthReady
          broadcastable: false

    school:
      address: schools
      identifier: id
      messageTypes:
        - name: createSchool
        - name: updateSchool
        - name: retrieveSchool
        - name: retrieveSchools
        - name: archiveSchool

    schoolApplication:
      address: applications
      identifier: id
      messageTypes:
        - name: createApplication
        - name: updateApplication
        - name: retrieveApplication
        - name: retrieveApplications
        - name: archiveApplication
        - name: retrieveApplicationsAnalytics
      config:
        templates:
          applicationConfirmation:
            template:
              path: $workingDir/src/main/resources/templates/school-application-confirmation-(messageType).hbs
              params:
                title: School Application - Confirmation
                signature: The Pinnacl Team
                supportEmail: (supportEmail)
                plazzaaLogoUrl: https://s3.eu-west-2.amazonaws.com/dev.pinnacl.dev/asset/74e79038-8488-4aec-ac8a-faf321a6a488/20240610120642563/logo.png
          applicationStatus:
            template:
              path: $workingDir/src/main/resources/templates/school-application-status-(messageType).hbs
              params:
                title: School Application (status)
                signature: The Pinnacl Team
                supportEmail: (supportEmail)
                plazzaaLogoUrl: https://s3.eu-west-2.amazonaws.com/dev.pinnacl.dev/asset/74e79038-8488-4aec-ac8a-faf321a6a488/20240610120642563/logo.png
        notifications:
          onCreateOrUpdate:
            sendEmail: true

    language:
      address: languages
      identifier: id
      messageTypes:
        - name: retrieveLanguages
        - name: retrieveLanguage
