service:
  name: academics
  displayName: Pinnacl Project - Academics Service
  address: io.pinnacl.academics
  sharedData:
    enabled: true
    extraMaps:
      - gateway
      - refreshTokens
      - totps
      - languages

observability:
  enabled: false
  port: 9092
  metrics:
    enabled: true
    path: /metrics
  k8s:
    enabled: true
    probes:
      liveness: /health/live
      readiness: /health/ready


storage:
  db:
    host: localhost
    port: 5432
    name: pinnacl-academics
    user: luffy
    password: we-do-not-store-secrets-in-source-control
    url: jdbc:postgresql://localhost:5432/pinnacl-academics
    useTls: false
    certPath: /tmp/dummy-cert.pem
    maxPool: 5
    migration:
      enabled: true
      changelogPath: migrations/changelog/db.changelog-dev.xml


features:
  verticles:
    service:
      address: service.details
      messageTypes:
        - name: academicsVersion
          broadcastable: false
        - name: academicsHealthLive
          broadcastable: false
        - name: academicsHealthReady
          broadcastable: false

    school:
      address: schools
      identifier: id
      messageTypes:
        - name: createSchool
        - name: updateSchool
        - name: retrieveSchool
        - name: retrieveSchools
        - name: archiveSchool
#        - name: retrieveApplicationsAnalytics

#    application:
#      address: applications
#      identifier: id
#      messageTypes:
#        - name: createAcademicApplication
#        - name: updateAcademicApplication
#        - name: retrieveAcademicApplication
#        - name: retrieveAcademicApplications
#        - name: archiveAcademicApplication
#      config:
#        templates:
#          applicationConfirmation:
#            template:
#              path: $workingDir/src/main/resources/templates/school-application-confirmation-(messageType).hbs
#              params:
#                title: School Admission - Confirmation
#                signature: The Pinnacl Team
#                supportEmail: (supportEmail)
#                plazzaaLogoUrl: https://s3.eu-west-2.amazonaws.com/dev.pinnacl.dev/asset/74e79038-8488-4aec-ac8a-faf321a6a488/20240610120642563/logo.png
#          applicationStatus:
#            template:
#              path: $workingDir/src/main/resources/templates/school-application-status-(messageType).hbs
#              params:
#                title: School Admission (status)
#                signature: The Pinnacl Team
#                supportEmail: (supportEmail)
#                plazzaaLogoUrl: https://s3.eu-west-2.amazonaws.com/dev.pinnacl.dev/asset/74e79038-8488-4aec-ac8a-faf321a6a488/20240610120642563/logo.png
#        notifications:
#          onCreateOrUpdate:
#            sendEmail: true
