apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-jvm-configmap" (include "pinnacl-commons.fullname" .) }}
data:
  JAVA_TOOL_OPTIONS: |-
    -XX:InitialRAMPercentage=50
    -XX:MaxRAMPercentage=50
    -XX:MinHeapFreeRatio=5
    -XX:MaxHeapFreeRatio=10
    --add-modules=java.se
    --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED
    --add-opens=java.base/java.lang=ALL-UNNAMED
    --add-opens=java.base/java.nio=ALL-UNNAMED
    --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
    --add-opens=java.management/sun.management=ALL-UNNAMED
    --add-opens=jdk.management/com.ibm.lang.management.internal=ALL-UNNAMED
    --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED