{{- $dbSecrets := (lookup "v1" "Secret" .Release.Namespace (printf "%s-pguser-%s" .Values.database.name .Values.database.instance.user)) }}
{{- if $dbSecrets }}
{{- $password := index $dbSecrets.data "password" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-db-secret" (include "pinnacl-commons.fullname" .) }}
type: Opaque
data:
  DB_PASSWORD: {{ $password }}
{{- end }}